apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv
spec:
  storageClassName: "first-storage-class"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: first-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/backend11-pj3/zones/us-central1-c/disks/my-first-disk
    fsType: ext4
