apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: first-pvc
spec:
  storageClassName: "first-storage-class"
  volumeName: first-pv 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
